import asyncio
from datetime import date
from database import engine, async_session, Base, Menu

MOCK_MENU = {
    "date": str(date.today()),
    "timeRange": {"from": "10:00", "to": "16:00"},
    "namespace": "cafeteria-main",
    "categories": [
        {"id": "salads", "name": "Салаты", "icon": "🥗"},
        {"id": "soups", "name": "Супы", "icon": "🍲"},
        {"id": "hot", "name": "Горячее", "icon": "🍳"},
        {"id": "sides", "name": "Гарниры", "icon": "🍚"},
        {"id": "drinks", "name": "Напитки", "icon": "☕"},
        {"id": "desserts", "name": "Десерты", "icon": "🍰"},
        {"id": "business-lunch", "name": "Бизнес ланч", "icon": "🍽️"},
    ],
    "dishes": [
        {
            "id": 1,
            "name": "Салат «Цезарь» с курицей",
            "category": "salads",
            "price": 320,
            "weight": 250,
            "calories": 280,
            "protein": 22,
            "fat": 16,
            "carbs": 12,
            "composition": "Куриное филе, салат романо, пармезан, сухарики, соус «Цезарь», помидоры черри",
            "isDietary": False,
            "isPromo": False,
        },
        {
            "id": 2,
            "name": "Салат «Греческий»",
            "category": "salads",
            "price": 280,
            "weight": 220,
            "calories": 190,
            "protein": 8,
            "fat": 14,
            "carbs": 10,
            "composition": "Огурцы, помидоры, перец болгарский, маслины, сыр фета, оливковое масло, орегано",
            "isDietary": True,
            "isPromo": False,
        },
        {
            "id": 3,
            "name": "Салат «Витаминный»",
            "category": "salads",
            "price": 180,
            "weight": 200,
            "calories": 95,
            "protein": 3,
            "fat": 5,
            "carbs": 11,
            "composition": "Капуста свежая, морковь, яблоко, лимонный сок, оливковое масло",
            "isDietary": True,
            "isPromo": True,
        },
        {
            "id": 4,
            "name": "Борщ украинский",
            "category": "soups",
            "price": 250,
            "weight": 350,
            "calories": 220,
            "protein": 12,
            "fat": 10,
            "carbs": 22,
            "composition": "Свёкла, картофель, капуста, морковь, лук, томатная паста, говядина, сметана",
            "isDietary": False,
            "isPromo": False,
        },
        {
            "id": 5,
            "name": "Крем-суп грибной",
            "category": "soups",
            "price": 270,
            "weight": 300,
            "calories": 180,
            "protein": 6,
            "fat": 12,
            "carbs": 14,
            "composition": "Шампиньоны, картофель, сливки 20%, лук репчатый, чеснок, тимьян",
            "isDietary": False,
            "isPromo": False,
        },
        {
            "id": 6,
            "name": "Куриная грудка на гриле",
            "category": "hot",
            "price": 350,
            "weight": 200,
            "calories": 310,
            "protein": 38,
            "fat": 12,
            "carbs": 4,
            "composition": "Куриная грудка, специи, оливковое масло, лимон",
            "isDietary": True,
            "isPromo": False,
        },
        {
            "id": 7,
            "name": "Котлета по-киевски",
            "category": "hot",
            "price": 380,
            "weight": 220,
            "calories": 420,
            "protein": 25,
            "fat": 28,
            "carbs": 18,
            "composition": "Куриное филе, сливочное масло, зелень, панировочные сухари, яйцо",
            "isDietary": False,
            "isPromo": False,
        },
        {
            "id": 8,
            "name": "Лосось запечённый",
            "category": "hot",
            "price": 520,
            "weight": 180,
            "calories": 340,
            "protein": 32,
            "fat": 20,
            "carbs": 6,
            "composition": "Филе лосося, лимон, прованские травы, оливковое масло, чеснок",
            "isDietary": False,
            "isPromo": True,
        },
        {
            "id": 9,
            "name": "Рис отварной",
            "category": "sides",
            "price": 90,
            "weight": 200,
            "calories": 260,
            "protein": 5,
            "fat": 1,
            "carbs": 58,
            "composition": "Рис длиннозёрный, вода, соль, масло сливочное",
            "isDietary": True,
            "isPromo": False,
        },
        {
            "id": 10,
            "name": "Картофельное пюре",
            "category": "sides",
            "price": 100,
            "weight": 200,
            "calories": 220,
            "protein": 4,
            "fat": 8,
            "carbs": 34,
            "composition": "Картофель, молоко, масло сливочное, соль, мускатный орех",
            "isDietary": False,
            "isPromo": False,
        },
        {
            "id": 11,
            "name": "Овощи на пару",
            "category": "sides",
            "price": 120,
            "weight": 180,
            "calories": 85,
            "protein": 3,
            "fat": 2,
            "carbs": 14,
            "composition": "Брокколи, цветная капуста, морковь, стручковая фасоль",
            "isDietary": True,
            "isPromo": False,
        },
        {
            "id": 12,
            "name": "Компот из сухофруктов",
            "category": "drinks",
            "price": 80,
            "weight": 250,
            "calories": 90,
            "protein": 0,
            "fat": 0,
            "carbs": 22,
            "composition": "Курага, чернослив, изюм, яблоки сушёные, сахар, вода",
            "isDietary": False,
            "isPromo": False,
        },
        {
            "id": 13,
            "name": "Чай чёрный",
            "category": "drinks",
            "price": 60,
            "weight": 200,
            "calories": 5,
            "protein": 0,
            "fat": 0,
            "carbs": 1,
            "composition": "Чай чёрный листовой",
            "isDietary": True,
            "isPromo": False,
        },
        {
            "id": 14,
            "name": "Морс клюквенный",
            "category": "drinks",
            "price": 90,
            "weight": 250,
            "calories": 70,
            "protein": 0,
            "fat": 0,
            "carbs": 17,
            "composition": "Клюква, сахар, вода",
            "isDietary": False,
            "isPromo": False,
        },
        {
            "id": 15,
            "name": "Тирамису",
            "category": "desserts",
            "price": 280,
            "weight": 150,
            "calories": 380,
            "protein": 8,
            "fat": 22,
            "carbs": 38,
            "composition": "Маскарпоне, печенье савоярди, кофе эспрессо, какао, яйца, сахар",
            "isDietary": False,
            "isPromo": False,
        },
        {
            "id": 16,
            "name": "Панна-котта",
            "category": "desserts",
            "price": 220,
            "weight": 130,
            "calories": 290,
            "protein": 5,
            "fat": 18,
            "carbs": 28,
            "composition": "Сливки, сахар, ваниль, желатин, ягодный соус",
            "isDietary": False,
            "isPromo": True,
        },
    ],
    "businessLunch": {
        "price": 350,
        "items": [
            {"id": 101, "name": "Салат «Весенний»", "category": "salads", "weight": 150, "calories": 120, "protein": 4, "fat": 7, "carbs": 10, "composition": "Огурцы, помидоры, зелень, сметана", "isDietary": True},
            {"id": 102, "name": "Салат «Оливье»", "category": "salads", "weight": 150, "calories": 180, "protein": 7, "fat": 12, "carbs": 14, "composition": "Картофель, морковь, яйцо, горошек, колбаса, майонез", "isDietary": False},
            {"id": 103, "name": "Салат из свежей капусты", "category": "salads", "weight": 130, "calories": 65, "protein": 2, "fat": 3, "carbs": 8, "composition": "Капуста белокочанная, морковь, укроп, масло растительное", "isDietary": True},
            {"id": 201, "name": "Суп куриный с лапшой", "category": "soups", "weight": 300, "calories": 160, "protein": 14, "fat": 6, "carbs": 12, "composition": "Курица, лапша яичная, морковь, лук, зелень", "isDietary": False},
            {"id": 202, "name": "Щи из свежей капусты", "category": "soups", "weight": 300, "calories": 130, "protein": 8, "fat": 5, "carbs": 14, "composition": "Капуста, картофель, морковь, лук, томатная паста, говядина", "isDietary": False},
            {"id": 203, "name": "Суп-пюре овощной", "category": "soups", "weight": 280, "calories": 95, "protein": 3, "fat": 4, "carbs": 12, "composition": "Цветная капуста, кабачок, морковь, картофель, сливки", "isDietary": True},
            {"id": 301, "name": "Гуляш из говядины", "category": "hot", "weight": 200, "calories": 280, "protein": 24, "fat": 16, "carbs": 10, "composition": "Говядина, лук, томатная паста, мука, специи", "isDietary": False},
            {"id": 302, "name": "Куриная котлета паровая", "category": "hot", "weight": 150, "calories": 190, "protein": 22, "fat": 8, "carbs": 6, "composition": "Куриное филе, лук, хлеб белый, яйцо, специи", "isDietary": True},
            {"id": 303, "name": "Рыба запечённая с овощами", "category": "hot", "weight": 180, "calories": 210, "protein": 26, "fat": 10, "carbs": 4, "composition": "Минтай, кабачок, морковь, лук, сметана, укроп", "isDietary": True},
            {"id": 401, "name": "Пюре картофельное", "category": "sides", "weight": 200, "calories": 220, "protein": 4, "fat": 8, "carbs": 34, "composition": "Картофель, молоко, масло сливочное, соль", "isDietary": False},
            {"id": 402, "name": "Гречка отварная", "category": "sides", "weight": 200, "calories": 200, "protein": 7, "fat": 3, "carbs": 38, "composition": "Крупа гречневая, вода, соль, масло сливочное", "isDietary": True},
            {"id": 403, "name": "Макароны отварные", "category": "sides", "weight": 200, "calories": 240, "protein": 6, "fat": 2, "carbs": 48, "composition": "Макаронные изделия, вода, соль, масло сливочное", "isDietary": False},
            {"id": 501, "name": "Чай чёрный", "category": "drinks", "weight": 200, "calories": 5, "protein": 0, "fat": 0, "carbs": 1, "composition": "Чай чёрный листовой", "isDietary": True},
            {"id": 502, "name": "Компот из сухофруктов", "category": "drinks", "weight": 200, "calories": 80, "protein": 0, "fat": 0, "carbs": 20, "composition": "Курага, чернослив, изюм, яблоки сушёные, сахар", "isDietary": False},
            {"id": 503, "name": "Кисель ягодный", "category": "drinks", "weight": 200, "calories": 70, "protein": 0, "fat": 0, "carbs": 17, "composition": "Ягоды, сахар, крахмал, вода", "isDietary": False},
        ],
    },
}


async def seed():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with async_session() as session:
        menu = Menu(
            namespace="cafeteria-main",
            date=date.today(),
            menu_json=MOCK_MENU,
        )
        await session.merge(menu)
        await session.commit()
        print(f"Seeded menu for namespace='cafeteria-main', date={date.today()}")


if __name__ == "__main__":
    asyncio.run(seed())