// ============================================================
// Mock data — замените содержимое функций на реальные fetch-вызовы
// ============================================================

const MOCK_MENU = {
  date: "2025-01-20",
  timeRange: { from: "10:00", to: "16:00" },
  namespace: "cafeteria-main",
  categories: [
    { id: "salads", name: "Салаты", icon: "🥗" },
    { id: "soups", name: "Супы", icon: "🍲" },
    { id: "hot", name: "Горячее", icon: "🍳" },
    { id: "sides", name: "Гарниры", icon: "🍚" },
    { id: "drinks", name: "Напитки", icon: "☕" },
    { id: "desserts", name: "Десерты", icon: "🍰" },
    { id: "business-lunch", name: "Бизнес ланч", icon: "🍽️" },
  ],
  dishes: [
    {
      id: 1,
      name: "Салат «Цезарь» с курицей",
      category: "salads",
      price: 320,
      weight: 250,
      calories: 280,
      protein: 22,
      fat: 16,
      carbs: 12,
      composition: "Куриное филе, салат романо, пармезан, сухарики, соус «Цезарь», помидоры черри",
      isDietary: false,
      isPromo: false,
    },
    {
      id: 2,
      name: "Салат «Греческий»",
      category: "salads",
      price: 280,
      weight: 220,
      calories: 190,
      protein: 8,
      fat: 14,
      carbs: 10,
      composition: "Огурцы, помидоры, перец болгарский, маслины, сыр фета, оливковое масло, орегано",
      isDietary: true,
      isPromo: false,
    },
    {
      id: 3,
      name: "Салат «Витаминный»",
      category: "salads",
      price: 180,
      weight: 200,
      calories: 95,
      protein: 3,
      fat: 5,
      carbs: 11,
      composition: "Капуста свежая, морковь, яблоко, лимонный сок, оливковое масло",
      isDietary: true,
      isPromo: true,
    },
    {
      id: 4,
      name: "Борщ украинский",
      category: "soups",
      price: 250,
      weight: 350,
      calories: 220,
      protein: 12,
      fat: 10,
      carbs: 22,
      composition: "Свёкла, картофель, капуста, морковь, лук, томатная паста, говядина, сметана",
      isDietary: false,
      isPromo: false,
    },
    {
      id: 5,
      name: "Крем-суп грибной",
      category: "soups",
      price: 270,
      weight: 300,
      calories: 180,
      protein: 6,
      fat: 12,
      carbs: 14,
      composition: "Шампиньоны, картофель, сливки 20%, лук репчатый, чеснок, тимьян",
      isDietary: false,
      isPromo: false,
    },
    {
      id: 6,
      name: "Куриная грудка на гриле",
      category: "hot",
      price: 350,
      weight: 200,
      calories: 310,
      protein: 38,
      fat: 12,
      carbs: 4,
      composition: "Куриная грудка, специи, оливковое масло, лимон",
      isDietary: true,
      isPromo: false,
    },
    {
      id: 7,
      name: "Котлета по-киевски",
      category: "hot",
      price: 380,
      weight: 220,
      calories: 420,
      protein: 25,
      fat: 28,
      carbs: 18,
      composition: "Куриное филе, сливочное масло, зелень, панировочные сухари, яйцо",
      isDietary: false,
      isPromo: false,
    },
    {
      id: 8,
      name: "Лосось запечённый",
      category: "hot",
      price: 520,
      weight: 180,
      calories: 340,
      protein: 32,
      fat: 20,
      carbs: 6,
      composition: "Филе лосося, лимон, прованские травы, оливковое масло, чеснок",
      isDietary: false,
      isPromo: true,
    },
    {
      id: 9,
      name: "Рис отварной",
      category: "sides",
      price: 90,
      weight: 200,
      calories: 260,
      protein: 5,
      fat: 1,
      carbs: 58,
      composition: "Рис длиннозёрный, вода, соль, масло сливочное",
      isDietary: true,
      isPromo: false,
    },
    {
      id: 10,
      name: "Картофельное пюре",
      category: "sides",
      price: 100,
      weight: 200,
      calories: 220,
      protein: 4,
      fat: 8,
      carbs: 34,
      composition: "Картофель, молоко, масло сливочное, соль, мускатный орех",
      isDietary: false,
      isPromo: false,
    },
    {
      id: 11,
      name: "Овощи на пару",
      category: "sides",
      price: 120,
      weight: 180,
      calories: 85,
      protein: 3,
      fat: 2,
      carbs: 14,
      composition: "Брокколи, цветная капуста, морковь, стручковая фасоль",
      isDietary: true,
      isPromo: false,
    },
    {
      id: 12,
      name: "Компот из сухофруктов",
      category: "drinks",
      price: 80,
      weight: 250,
      calories: 90,
      protein: 0,
      fat: 0,
      carbs: 22,
      composition: "Курага, чернослив, изюм, яблоки сушёные, сахар, вода",
      isDietary: false,
      isPromo: false,
    },
    {
      id: 13,
      name: "Чай чёрный",
      category: "drinks",
      price: 60,
      weight: 200,
      calories: 5,
      protein: 0,
      fat: 0,
      carbs: 1,
      composition: "Чай чёрный листовой",
      isDietary: true,
      isPromo: false,
    },
    {
      id: 14,
      name: "Морс клюквенный",
      category: "drinks",
      price: 90,
      weight: 250,
      calories: 70,
      protein: 0,
      fat: 0,
      carbs: 17,
      composition: "Клюква, сахар, вода",
      isDietary: false,
      isPromo: false,
    },
    {
      id: 15,
      name: "Тирамису",
      category: "desserts",
      price: 280,
      weight: 150,
      calories: 380,
      protein: 8,
      fat: 22,
      carbs: 38,
      composition: "Маскарпоне, печенье савоярди, кофе эспрессо, какао, яйца, сахар",
      isDietary: false,
      isPromo: false,
    },
    {
      id: 16,
      name: "Панна-котта",
      category: "desserts",
      price: 220,
      weight: 130,
      calories: 290,
      protein: 5,
      fat: 18,
      carbs: 28,
      composition: "Сливки, сахар, ваниль, желатин, ягодный соус",
      isDietary: false,
      isPromo: true,
    },
  ],
  businessLunch: {
    price: 350,
    items: [
      {
        id: 101,
        name: "Салат «Весенний»",
        category: "salads",
        weight: 150,
        calories: 120,
        protein: 4,
        fat: 7,
        carbs: 10,
        composition: "Огурцы, помидоры, зелень, сметана",
        isDietary: true,
      },
      {
        id: 102,
        name: "Суп куриный с лапшой",
        category: "soups",
        weight: 300,
        calories: 160,
        protein: 14,
        fat: 6,
        carbs: 12,
        composition: "Курица, лапша яичная, морковь, лук, зелень",
        isDietary: false,
      },
      {
        id: 103,
        name: "Гуляш с гарниром",
        category: "hot",
        weight: 280,
        calories: 380,
        protein: 28,
        fat: 18,
        carbs: 26,
        composition: "Говядина, картофельное пюре, лук, томатная паста, мука, специи",
        isDietary: false,
      },
      {
        id: 104,
        name: "Чай или компот",
        category: "drinks",
        weight: 200,
        calories: 45,
        protein: 0,
        fat: 0,
        carbs: 11,
        composition: "На выбор: чай чёрный / компот из сухофруктов",
        isDietary: true,
      },
    ],
  },
};

// ============================================================
// API functions — замените тела на fetch() к реальному бэкенду
// ============================================================

const API_BASE_URL = "/api"; // Заменить на реальный URL

/**
 * Получить меню на текущую дату
 * @param {string} namespace - идентификатор точки кафетерия
 * @returns {Promise<object>}
 */
export async function fetchMenu(namespace = "cafeteria-main") {
  // === MOCK ===
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(MOCK_MENU);
    }, 400);
  });

  // === REAL API (раскомментировать) ===
  // const response = await fetch(`${API_BASE_URL}/menu?namespace=${namespace}`);
  // if (!response.ok) throw new Error('Failed to fetch menu');
  // return response.json();
}