export const mockDishes = [
  {
    id: '1',
    name: 'Борщ украинский',
    composition: 'Свёкла, капуста, картофель, морковь, лук, томатная паста, говядина',
    calories: 120,
    proteins: 8.5,
    fats: 4.2,
    carbs: 12.3,
    price: 350,
    weight: 350,
  },
  {
    id: '2',
    name: 'Цезарь с курицей',
    composition: 'Куриная грудка, салат романо, пармезан, гренки, соус цезарь',
    calories: 280,
    proteins: 22.0,
    fats: 16.5,
    carbs: 10.8,
    price: 520,
    weight: 280,
  },
  {
    id: '3',
    name: 'Стейк из сёмги',
    composition: 'Сёмга, лимон, оливковое масло, прованские травы, спаржа',
    calories: 310,
    proteins: 28.0,
    fats: 20.1,
    carbs: 2.4,
    price: 890,
    weight: 250,
  },
  {
    id: '4',
    name: 'Паста карбонара',
    composition: 'Спагетти, бекон, яйцо, пармезан, чёрный перец, сливки',
    calories: 350,
    proteins: 15.0,
    fats: 18.0,
    carbs: 35.0,
    price: 480,
    weight: 320,
  },
  {
    id: '5',
    name: 'Тирамису',
    composition: 'Маскарпоне, савоярди, эспрессо, какао, яйца, сахар',
    calories: 290,
    proteins: 6.0,
    fats: 16.0,
    carbs: 30.0,
    price: 420,
    weight: 180,
  },
];